scripts.d/ta/260_compare_dpdk_gateways.sh, scripts.d/ta/270_weka_local_resources_gateways.sh, scripts.d/ta/290_check_traces_free_space.sh, scripts.d/ta/330_nfs_v4_ip_address_failover.sh, scripts.d/ta/400_s3_using_etcd.sh, scripts.d/ta/460_ip_source-based_routing.sh, scripts.d/ta/490_ip_route_metrics.sh, scripts.d/ta/500_sysctl_rp_filter.sh, scripts.d/ta/510_check_for_noprefixroute.sh, scripts.d/ta/520_bucket_and_process_uptime.sh
At the moment we can only call shell scripts in wekachecker. This means that the natural solution to parse JSON is jq, but we can't rely on jq being available on default installations of older distributions (such as RHEL7).
As Python3 is more likely to be more widely installed (and these changes only require the sys, json, and collection modules, which are expected to be stable) it seems the only acceptable change is to remove the dependency on jq and move to Python3.
This has led to some less-readable code (in particular in the script 460_ip_source-based_routing.sh) so improvements are welcome.
=> Replace calls to jq with calls to python3 + json module

scripts.d/ta/540_check_for_obs_in_scarce_mode.sh
In WEKAPP-376458 there was a problem with NFS services getting stuck. The issue went through Protocols -> Driver -> Filesystem team before it was found that an OBS tier was in scarce mode, limiting backpressure's ability to free up NVMe space.
While this is not a diagnostic certainty, this simple test might direct investigation more accurately.
=> Added a very simple test to see if OBS tiers are in "Scarce" mode

scripts.d/ta/540_check_for_obs_in_scarce_mode.sh, scripts.d/ta/550_iptables_nats_local_traffic.sh, scripts.d/ta/560_check_for_swap.sh, scripts.d/ta/570_does_weka_use_swap.sh, scripts.d/ta/580_weka_version_available_everywhere.sh
wekachecker reportedly requires output even in the case of success
=> Cst jack allow success no output

scripts.d/ta/010_ping.sh, scripts.d/ta/125_checkinternet.sh, scripts.d/ta/490_ip_route_metrics.sh, scripts.d/ta/510_check_for_noprefixroute.sh, scripts.d/ta/540_check_for_obs_in_scarce_mode.sh, scripts.d/ta/550_iptables_nats_local_traffic.sh, scripts.d/ta/560_check_for_swap.sh, scripts.d/ta/570_does_weka_use_swap.sh, scripts.d/ta/580_weka_version_available_everywhere.sh, scripts.d/ta/590_single_dns_entry.sh
Add a check for the number of DNS A records, which should equal 1
SMB-W (at least) depends on having DNS working, and it *must* return
exactly 1 entry. Some customer sites use e.g. dynDNS, which creates
multiple DNS results which upsets PCS
=> Cst jack single dns entry

scripts.d/ta/620_same_mtu_across_nics.sh
As per https://wekaio.atlassian.net/browse/WEKAPP-316504 if a host has a link at >4k, we assume that all NICs are. While this is a bug, and will likely be fixed, it almost certainly will create PartiallyDisconnected nodes and/or communication problems between cluster containers
=> Add a test to check if one NIC MTU is > 4k, they all are

scripts.d/ta/630_opt_weka_exists_but_not_mounted.sh
in SFDC 13589 we encountered a situation in which the customer had configured an extra partition for /opt/weka, and defined it in /etc/fstab but had not actually mounted it.
All changes were made to /opt/weka on the rootFS.
When the system rebooted the weka containers were missing.
This script checks for the definition of an /opt/weka mountpoint in both fstab and systemd, and whether it's currently mounted (and the inverse).
This is not foolproof because you could still achieve the same confusion by e.g. doing similar with /opt rather than /opt/weka
=> Add a check to verify that /opt/weka is configured to mount at boot time

scripts.d/ta/640_opt_weka_is_not_symlink.sh
symlinks don't work because we do the equivalent of a chroot / unshare -m
=> Check /opt/weka is not a symlink

scripts.d/ta/590_single_dns_entry.sh, scripts.d/ta/600_fewer_than_16_numas.sh, scripts.d/ta/610_nfs_aliases_sbr.sh, scripts.d/ta/620_same_mtu_across_nics.sh, scripts.d/ta/630_opt_weka_exists_but_not_mounted.sh
Each of these tests needs to return some text even in the case of success.
Get rid of pointless quotes around lvalue.
=> Add in required text output in case of successful tests

scripts.d/ta/660_hugepages_check.sh
Checks to see if there is a discrepancy between the 2MiB and 1GiB pages allocated to Weka vs. what is reported as used by the OS.
=> Check for hugepages memory discrepancy

scripts.d/ta/690_auto_core_in_mcb.sh
In internal Slack
https://wekaio.slack.com/archives/C01RYT54NP4/p1717722025876539 we received explicit statement that we should not leave MCB containers to auto-assign CPUs, as it leads to a race condition between containers trying to grab the same core ID
=> Warn if any MCB containers use auto-allocated cores

scripts.d/ta/700_wekapp351707.sh
Check to see if clusters may be affected by the backpressure issue described in WEKAPP-351707.
=> Check for WEKAPP-351707

scripts.d/default/150_htcputest.sh, scripts.d/ta/150_htcputest.sh
Issue reported via Slack about parsing the output of cpuinfo, so... Rather than relying on the existence and output of dmidecode and /proc/cpuinfo, it actually makes more sense to read /sys/devices/system/cpu/smt/active, which is old, simple, and widely available.
I think it exists everywhere on kernel >2.6.
Fixed (assumed) typo about AMT -> SMT.
=> Simplify the test for Hyperthreading / SMT

scripts.d/ta/730_large_drives.sh
While this will likely never happen in production, I was requested to add a specific version-aware check
=> Initial check for 30 Tbyte drives in older versions

scripts.d/ta/490_ip_route_metrics.sh
The previous version warned simply if we had metrics set, but that's not precise enough; metrics only really matter if the routes have the same destination. Even then there has to be more than one metric-having route to the same destination for us to actually have a problem, therefore:
First find any routes that specify a route metric, then count them based on the same routing destination. A single route to a destination with a metric is fine (because the metric is meaningless there), but routes which specify the same destination *and* a metric is not likely to be useful. (There are circumstances where it makes sense, such as a backup/failover
route that's not intended to be preferred)
=> Limit warning to only those cases where the routing destinations match

scripts.d/ta/470_number_of_numa_domains.sh
The maximum number of NUMA domains, in 4.2.11+ and 4.3.2+, is 32, not 20. This change corrects this.
=> Increase number of supported NUMA domains from 20 to 32

scripts.d/ta/740_mlx_settings.sh
Checks to see if PCI_WR_ORDERING and ADVANCED_PCI_SETTINGS are set to 1 on Mellanox NICs.
=> Check Mellanox NIC settings

scripts.d/ta/775_dup_arp_check.sh
Check to see if the local ARP cache has duplicate entries for Weka management IPs.
=> Duplicate ARP check for management IPs

scripts.d/ta/223_checknvmelba.sh
Do not return a warning if an NVMe does not exist.
=> Check NVME LBA update

scripts.d/ta/805_lacp_hash_check.sh, scripts.d/ta/805_lag_hash_check.sh
New test to validate bonded interfaces:
- Check for xmit hash policy set to layer2
- Check for potential bonding across NICs
- Validate compatible NIC for LAG hashing
=> Simple LAG / LAG hashing configuration validation

scripts.d/ta/845_mem_alloc.sh
Check to ensure that at least 8 GiB, of total system memory, has not been allocated to Weka.
=> Check for minimally free OS memory

scripts.d/ta/740_mlx_settings.sh
Previously:
[root ]# mlxconfig -d /dev/mst/mt4123_pciconf1 q | awk '/PCI_WR_ORDERING/ && /(0)/' [root ]# echo $?
0
[root ]# mlxconfig -d /dev/mst/mt4123_pciconf1 q | awk '/PCI_WR_ORDERING/ && /(1)/'
PCI_WR_ORDERING                             force_relax(1)
[root ]# echo $?
0
therefore simplify a little to grep.
=> Bugfix: Previously relied on exit status of awk, which was a constant

scripts.d/ta/865_infiniband_lid_mismatch.sh
Checks to see if the Infiniband LID cached by Weka matches the Infiniband LID currently assigned to the NIC by the SM.
=> Check for Weka / Infiniband LID mismatches

scripts.d/ta/865_infiniband_lid_mismatch.sh
If the cluster is using PKEYs on Infiniband, then NIC names change from e.g. "ib3" to "ib3.8001". However, the LID information still exists under the base device name in sysfs, e.g.:
/sys/class/net/ibs3/device/infiniband/mlx5_0/ports/1/lid
This change allows the regex to match any character except dot, which seems a logical way of handling it.
=> Allow IB NIC Name matching to handle PKEY device names

scripts.d/ta/875_cgroup_validation.sh
New test to validate cgroups as used by Weka:
-Are they enabled?
-Are auto cores in use?
-Are they enabled, but some allocated CPUs are not constrained?
=> Validate cgroups

scripts.d/ta/880_all_mdadm_devices_good.sh
The WSA will auto-create mdadm RAID1 devices if there are two small hardware drives, and use those as boot devices. In SFDC 00018153 some drives got out of sync due to a firmware update, and nothing reports on that. The symptom was that changes in /boot where not being reflected in the boot loader because the device GRUB was loading from wasn't being updated.
=> Check all mdadm devices report as OK

scripts.d/ta/885_nfsw_fds.sh
Raise a warning if the current NFSW FD usage is >=90% of the configured maximum.
=> Query NFSW FD usage

scripts.d/ta/890_hot_spare_capacity.sh
Clusters with 0 hot-spare can potentially be configured to allocate and use ~100% of SSD capacity. In the case of loss of a failure domain they'll lose a proportion of FS space (known as shrinkage). The proportion lost is dependent on the number of data disks, and if "too much" is lost then writes can fail with ENOSPACE.
Essentially, we should warn customers without hot spares configured
=> Add a very basic capacity check in the case of 0 hot-spare clusters

scripts.d/ta/910_disparate_bucket_fill_level.sh
We don't want weka cluster buckets becoming too full, or too imbalanced. Ordinarily the RAID stripe allocation takes care of this for us, but in at least https://wekaio.atlassian.net/browse/WEKAPP-488736 (for example) network interruptions led to us not being able to find free stripes. This in turn led to buckets becoming full and thus FS writes stalling.
=> Add a check to examine bucket fill levels

scripts.d/ta/900_check_link_speeds.sh
In https://wekaio.atlassian.net/browse/WEKAPP-482528 we saw that the link speed was lower than expected, but there were no warnings. We should check that.
The only plausible way I can find of doing this is by parsing the text-based output of ethtool, until jq and "ethtool --json" get everywhere, or the kernel interface to ethtool-netlink is exposed in /sys, I can't see any other way of doing it. :(
=> Basic checker to compare current NIC link speed with maximum

scripts.d/ta/460_ip_source-based_routing.sh
Previously we assumed that 'ip rule' would output with the table name at the very end of the line. Depending on how that rule is added it might not be; it could be e.g.
32764:  from 10.31.62.119 lookup 100 proto static
Therefore instead capture "the word after 'lookup'" instead.
=> Allow the lookup table to be anywhere in the output of 'ip rule'

scripts.d/ta/635_loopback_fs_free_space.sh
In WEKAPP-527332 we saw that a full loopback XFS filesystem at
/opt/weka/data/drives0/container/reserved.loop
prevented many things (such as the traces, nginx for the API) from starting, with almost *no* error messages whatsoever.
=> Ensure sufficient freespace in loopback filesystems exist
