weka/wekachecker

report.py
wekachecker.py

Ta tool empty responses and crashes

---

scripts.d/ta/540_check_for_obs_in_scarce_mode.sh
scripts.d/ta/550_iptables_nats_local_traffic.sh
scripts.d/ta/560_check_for_swap.sh
scripts.d/ta/570_does_weka_use_swap.sh

Need to check if swap is configured at all (probably not helpful)
Need to check if swap is in use by a weka-container process (probably actively bad)

Cst jack check for swap

---

scripts.d/ta/580_weka_version_available_everywhere.sh

Check that cluster version is the current default of all local agents

---

scripts.d/ta/010_ping.sh
scripts.d/ta/125_checkinternet.sh
scripts.d/ta/490_ip_route_metrics.sh
scripts.d/ta/510_check_for_noprefixroute.sh
scripts.d/ta/540_check_for_obs_in_scarce_mode.sh
scripts.d/ta/550_iptables_nats_local_traffic.sh
scripts.d/ta/560_check_for_swap.sh
scripts.d/ta/570_does_weka_use_swap.sh
scripts.d/ta/580_weka_version_available_everywhere.sh
scripts.d/ta/590_single_dns_entry.sh
scripts.d/ta/600_fewer_than_16_numas.sh

Warn if more than 16 NUMA regions, as per WEKAPP-342965

Cst jack fewer than 16 numas

---

scripts.d/ta/520_bucket_and_process_uptime.sh

up_since can return the string "None", which can't be converted to seconds since epoch.

Bugfix: correctly handle brand new (unstarted) clusters with no uptime

---

scripts.d/ta/670_crowdstrike_check.sh

Checks systemd for running CrowdStrike Falcon Sensor

Check to see if CrowdStrike Falcon Sensor is running

---

scripts.d/ta/135_checkdns.sh
scripts.d/ta/160_checkaes.sh
scripts.d/ta/610_nfs_aliases_sbr.sh

fix up from customer site tests.
Made a few changes to the NFS testing, hence request @vrragosta 's eyeballs; seems sensible to short-circuit the test, but reasoning is in commit logs

Cst jack code fixup trex

---

scripts.d/ta/195_ofed.sh

- Add missing OFED versions that are currently supported
- Code cleanup

Check for all supported OFED versions

---

scripts.d/ta/710_no_spaces_in_cluster_name.sh

vim typo fix number 2

---

scripts.d/ta/755_wekapp424920_smbw_mask.sh

Check to see if force_create_mode and force_directory_mode are defined on smbw shares.

WEKAPP-424920 - SMBW tsmb.conf mask check

---

scripts.d/ta/765_process_network_mode.sh

Checks to ensure all compute and drives processes have equivalent network modes.

Check for process network mode consistency

---

scripts.d/ta/030_dup_uuid_check.sh

Inspects the weka cluster container output for 2-tuple hostname / machine identifier duplicates.

Check containers for duplicate machine identifiers

---

scripts.d/ta/755_wekapp424920_smbw_mask.sh

Remove incorrect comments to appease Seth.

Remove incorrect comments from WEKAPP-424920 check

---

scripts.d/ta/785_asymmetric_mtu.sh

- Initial commit for asymmetric MTU check -- flag any processes where the in MTU differs from the out MTU.

Create asymmetric MTU check

---

scripts.d/ta/620_same_mtu_across_nics.sh

- Remove dependency on being logged into Weka
- Exclude envoy and samba containers
- Ensure /sys path returns value

Same MTU update

---

scripts.d/ta/580_weka_version_available_everywhere.sh

- Check to see if weka user logged in
- Remove python dependency
- Obtain agent version from weka local status output

Weka version everwhere update

---

scripts.d/ta/650_firewall_check_quick.sh

- Change from parallel to single execution
- Remove weka login dependency
- Remove dependency on nc
- Check all tcp/udp management ports

Rewrite firewall check

---

scripts.d/ta/795_netmask_mismatch.sh

New test that checks to see if the netmask configured in the container resources matches the one on the interface in the OS.

Create test to check for netmask inconsistencies

---

scripts.d/ta/195_ofed.sh

Return all potential misconfiguration issues.

Update OFED check

---

scripts.d/ta/810_use_only_readcache_for_protocols.sh
scripts.d/ta/815_no_spaces_in_fs_name.sh

I gave the branch a stupid name but whatever

Cst jack no spaces in filesystem names

---

scripts.d/ta/825_ha_mgmt_ip.sh

Ensure each Weka dataplane NIC has a corresponding management IP defined in each of the container's resource configuration.

Dataplane mgmt ip check

---

scripts.d/ta/835_s2o_unmigrated.sh

Initial commit -- check if a filesystem, downloaded via Snap2Obj, is still associated with the source bucket.

S2O unmigrated check

---

scripts.d/ta/650_firewall_check_quick.sh

Remove dependency on weka local status, instead querying the cluster's container configuration.

Update firewall quick check

---

scripts.d/ta/460_ip_source-based_routing.sh

- Remove dependency on Python
- Only validate relevant dataplane NICs
- Additionally check arp_ignore

Update source-based routing checks

---

scripts.d/default/145_checkwekapackages.sh

- Update required package dependencies for Ubuntu 24
- General cleanup

Update of package dependencies check

---

scripts.d/ta/855_nfsw_fips_sanity.sh

-Added additional check for ver.value > 16k (WEKAPP-471021)
-Addressed logic flaws in string matching

Update NFSW FIPS checks

---

scripts.d/client/110_checkos.sh
scripts.d/client/130_checkntp.sh
scripts.d/client/195_ofed.sh
scripts.d/default/110_checkos.sh
scripts.d/default/130_checkntp.sh
scripts.d/default/195_ofed.sh
scripts.d/default/200_checkiommu.sh

Updated NTP to check for Timesyncd
Updated OS for newer distros supported
Update IOMMU to allow it
Updated OFED to support newer versions

Changes for Weka4 - OS, IOMMU and NTP & OFED

---

scripts.d/ta/460_ip_source-based_routing.sh
scripts.d/ta/550_iptables_nats_local_traffic.sh
scripts.d/ta/795_netmask_mismatch.sh
scripts.d/ta/825_ha_mgmt_ip.sh
scripts.d/ta/855_nfsw_fips_sanity.sh

- Provide IPv6 support in FIPs sanity, mgmt IP, netmask and SBR checks
- Remove jq dependency in NATS check

IPv6 updates and code cleanup

---

scripts.d/ta/865_infiniband_lid_mismatch.sh

Need to iterate over all compute / drive / frontend containers.

Update Infiniband LID mismatch check

---

scripts.d/ta/935_container_resource_alloc.sh

Additionally check for core allocation consistency

Update container resource check

---

scripts.d/ta/945_obs_conn_check.sh

Basic OBS connectivity checks:
-DNS resolves
-IP/Port endpoint socket reachable
-Outlier RTT endpoints?
-OBS Server error codes past 30 minutes?

Create basic OBS connectivity checks

---

scripts.d/ta/765_process_network_mode.sh

Perform net port consistency checks for all backend compute / drive / frontend processes.

Update network mode test
